export const ourProducts_data = [
    {
        discountBadge: false,
        discountPrice: 45,
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,

        src: "/card1.png",
        heading: "Breed Dry Dog Food",
        newPrice: 100,
        star: 3,
        revews: 35,
        colorDiv: false,
    },
    {
        discountBadge: false,
        discountPrice: 45,
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,

        src: "/card1.png",
        heading: "CANON EOS DSLR Camera",
        newPrice: 360,
        star: 4,
        revews: 95,
        colorDiv: false,
    },
    {
        discountBadge: false,
        discountPrice: 45,
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,

        src: "/card1.png",
        heading: "CANON EOS DSLR Camera",
        newPrice: 360,
        star: 4,
        revews: 95,
        colorDiv: false,
    },
    {
        discountBadge: false,
        discountPrice: 45,
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,

        src: "/card1.png",
        heading: "CANON EOS DSLR Camera",
        newPrice: 360,
        star: 4,
        revews: 95,
        colorDiv: false,
    },
    {
        discountBadge: true,
        discountPrice: "New",
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,

        src: "/card1.png",
        heading: "CANON EOS DSLR Camera",
        newPrice: 960,
        star: 5,
        revews: 65,
        colorDiv: true,
        color1: "bg-black",
        color2: "red",
    },
    {
        discountBadge: false,
        discountPrice: 45,
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,

        src: "/card1.png",
        heading: "CANON EOS DSLR Camera",
        newPrice: 360,
        star: 4,
        revews: 95,
        colorDiv: true,
        color1: "bg-black",
        color2: "red",

    },
    {
        discountBadge: true,
        discountPrice: "New",
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,

        src: "/card1.png",
        heading: "CANON EOS DSLR Camera",
        newPrice: 660,
        star: 5,
        revews: 55,
        colorDiv: true,
        color1: "bg-black",
        color2: "red",
    },
    {
        discountBadge: false,
        discountPrice: 45,
        trashIcon: false,
        heartIcon: true,
        eyeIcon: true,

        src: "/card1.png",
        heading: "CANON EOS DSLR Camera",
        newPrice: 360,
        star: 4,
        revews: 95,
        colorDiv: true,
        color1: "bg-black",
        color2: "red",
    },
]